#include "system.h"

void ErrorReport(int errorNum, char* ecode) 
{
    if(errorNum == 0 )                strcpy(ecode, "(No Error occurred)");
    else if(errorNum == EPERM  )      strcpy(ecode, "(Operation not permitted )");
    else if(errorNum == ENOENT )      strcpy(ecode, "(No such file or directory )");
    else if(errorNum == ESRCH  )      strcpy(ecode, "(No such process )");
    else if(errorNum == EINTR  )      strcpy(ecode, "(Interrupted system call )");
    else if(errorNum == EIO    )      strcpy(ecode, "(I/O error )");
    else if(errorNum == ENXIO  )      strcpy(ecode, "(No such device or address )");
    else if(errorNum == E2BIG  )      strcpy(ecode, "(Argument list too long )");
    else if(errorNum == ENOEXEC )     strcpy(ecode, "(Exec format error )");
    else if(errorNum == EBADF   )     strcpy(ecode, "(Bad file number )");
    else if(errorNum == ECHILD  )     strcpy(ecode, "(No child processes )");
    else if(errorNum == EAGAIN  )     strcpy(ecode, "(Try again )");
    else if(errorNum == ENOMEM  )     strcpy(ecode, "(Out of memory )");
    else if(errorNum == EACCES  )     strcpy(ecode, "(Permission denied )");
    else if(errorNum == EFAULT  )     strcpy(ecode, "(Bad address )");
    else if(errorNum == ENOTBLK )     strcpy(ecode, "(Block device required )");
    else if(errorNum == EBUSY   )     strcpy(ecode, "(Device or resource busy )");
    else if(errorNum == EEXIST  )     strcpy(ecode, "(File exists )");
    else if(errorNum == EXDEV   )     strcpy(ecode, "(Cross-device link )");
    else if(errorNum == ENODEV  )     strcpy(ecode, "(No such device )");
    else if(errorNum == ENOTDIR )     strcpy(ecode, "(Not a directory )");
    else if(errorNum == EISDIR  )     strcpy(ecode, "(Is a directory )");
    else if(errorNum == EINVAL  )     strcpy(ecode, "(Invalid argument )");
    else if(errorNum == ENFILE  )     strcpy(ecode, "(File table overflow )");
    else if(errorNum == EMFILE  )     strcpy(ecode, "(Too many open files )");
    else if(errorNum == ENOTTY  )     strcpy(ecode, "(Not a typewriter )");
    else if(errorNum == ETXTBSY )     strcpy(ecode, "(Text file busy )");
    else if(errorNum == EFBIG   )     strcpy(ecode, "(File too large )");
    else if(errorNum == ENOSPC  )     strcpy(ecode, "(No space left on device )");
    else if(errorNum == ESPIPE  )     strcpy(ecode, "(Illegal seek )");
    else if(errorNum == EROFS   )     strcpy(ecode, "(Read-only file system )");
    else if(errorNum == EMLINK  )     strcpy(ecode, "(Too many links )");
    else if(errorNum == EPIPE   )     strcpy(ecode, "(Broken pipe )");
    else if(errorNum == EDOM    )     strcpy(ecode, "(Math argument out of domain of func )");
    else if(errorNum == ERANGE  )     strcpy(ecode, "(Math result not representable )");

    else if(errorNum == EDEADLK )  strcpy(ecode, "(Resource deadlock would occur )");
    else if(errorNum == ENAMETOOLONG )    strcpy(ecode, "(File name too long )");
    else if(errorNum == ENOLCK )    strcpy(ecode, "(No record locks available )");
    else if(errorNum == ENOSYS )    strcpy(ecode, "(Function not implemented )");
    else if(errorNum == ENOTEMPTY )    strcpy(ecode, "(Directory not empty)");
    else if(errorNum == ELOOP )    strcpy(ecode, "(Too many symbolic links encountered )");
//    else if(errorNum == EWOULDBLOCK EAGAIN  strcpy(ecode, "(Operation would block )");
    else if(errorNum == ENOMSG)    strcpy(ecode, "(No message of desired type )");
    else if(errorNum == EIDRM )    strcpy(ecode, "(Identifier removed )");
    else if(errorNum == ECHRNG)    strcpy(ecode, "(Channel number out of range )");
    else if(errorNum == EL2NSYNC)  strcpy(ecode, "(Level 2 not synchronized )");
    else if(errorNum == EL3HLT)    strcpy(ecode, "(Level 3 halted )");
    else if(errorNum == EL3RST)    strcpy(ecode, "(Level 3 reset )");
    else if(errorNum == ELNRNG )   strcpy(ecode, "(Link number out of range )");
    else if(errorNum == EUNATCH )    strcpy(ecode, "(Protocol driver not attached )");
    else if(errorNum == ENOCSI )    strcpy(ecode, "(No CSI structure available )");
    else if(errorNum == EL2HLT )    strcpy(ecode, "(Level 2 halted )");
    else if(errorNum == EBADE )    strcpy(ecode, "(Invalid exchange )");
    else if(errorNum == EBADR )    strcpy(ecode, "(Invalid request descriptor )");
    else if(errorNum == EXFULL )    strcpy(ecode, "(Exchange full )");
    else if(errorNum == ENOANO )    strcpy(ecode, "(No anode )");
    else if(errorNum == EBADRQC )    strcpy(ecode, "(Invalid request code )");
    else if(errorNum == EBADSLT )    strcpy(ecode, "(Invalid slot )");

//    else if(errorNum == EDEADLOCK   EDEADLK

    else if(errorNum == EBFONT )    strcpy(ecode, "(Bad font file format )");
    else if(errorNum == ENOSTR )    strcpy(ecode, "(Device not a stream )");
    else if(errorNum == ENODATA  )  strcpy(ecode, "(No data available )");
    else if(errorNum == ETIME    )  strcpy(ecode, "(Timer expired )");
    else if(errorNum == ENOSR    )  strcpy(ecode, "(Out of streams resources )");
    else if(errorNum == ENONET   )  strcpy(ecode, "(Machine is not on the network )");
    else if(errorNum == ENOPKG   )  strcpy(ecode, "(Package not installed )");
    else if(errorNum == EREMOTE  )  strcpy(ecode, "(Object is remote )");
    else if(errorNum == ENOLINK  )  strcpy(ecode, "(Link has been severed )");
    else if(errorNum == EADV     )  strcpy(ecode, "(Advertise error )");
    else if(errorNum == ESRMNT   )  strcpy(ecode, "(Srmount error )");
    else if(errorNum == ECOMM    )  strcpy(ecode, "(Communication error on send )");
    else if(errorNum == EPROTO   )  strcpy(ecode, "(Protocol error )");
    else if(errorNum == EMULTIHOP)  strcpy(ecode, "(Multihop attempted )");
    else if(errorNum == EDOTDOT  )  strcpy(ecode, "(RFS specific error )");
    else if(errorNum == EBADMSG  )   strcpy(ecode, "(Not a data message )");
    else if(errorNum == EOVERFLOW)     strcpy(ecode, "(Value too large for defined data type )");
    else if(errorNum == ENOTUNIQ )     strcpy(ecode, "(Name not unique on network )");
    else if(errorNum == EBADFD   )     strcpy(ecode, "(File descriptor in bad state )");
    else if(errorNum == EREMCHG  )     strcpy(ecode, "(Remote address changed )");
    else if(errorNum == ELIBACC  )  strcpy(ecode, "(Can not access a needed shared library )");
    else if(errorNum == ELIBBAD  )   strcpy(ecode, "(Accessing a corrupted shared library )");
    else if(errorNum == ELIBSCN  )   strcpy(ecode, "(.lib section in a.out corrupted )");
    else if(errorNum == ELIBMAX  )  strcpy(ecode, "(Attempting to link in too many shared libraries )");
    else if(errorNum == ELIBEXEC )  strcpy(ecode, "(Cannot exec a shared library directly )");
    else if(errorNum == EILSEQ   )  strcpy(ecode, "(Illegal byte sequence )");
    else if(errorNum == ERESTART )     strcpy(ecode, "(Interrupted system call should be restarted )");
    else if(errorNum == ESTRPIPE )     strcpy(ecode, "(Streams pipe error )");
    else if(errorNum == EUSERS   )     strcpy(ecode, "(Too many users )");
    else if(errorNum == ENOTSOCK )     strcpy(ecode, "(Socket operation on non-socket )");
    else if(errorNum == EDESTADDRREQ )  strcpy(ecode, "(Destination address required )");
    else if(errorNum == EMSGSIZE )   strcpy(ecode, "(Message too long )");
    else if(errorNum == EPROTOTYPE )  strcpy(ecode, "(Protocol wrong type for socket )");
    else if(errorNum == ENOPROTOOPT)  strcpy(ecode, "(Protocol not available )");
    else if(errorNum == EPROTONOSUPPORT)  strcpy(ecode, "(Protocol not supported )");
    else if(errorNum == ESOCKTNOSUPPORT)  strcpy(ecode, "(Socket type not supported )");
    else if(errorNum == EOPNOTSUPP )  strcpy(ecode, "(Operation not supported on transport endpoint )");
    else if(errorNum == EPFNOSUPPORT )     strcpy(ecode, "(Protocol family not supported )");
    else if(errorNum == EAFNOSUPPORT )     strcpy(ecode, "(Address family not supported by protocol )");
    else if(errorNum == EADDRINUSE )  strcpy(ecode, "(Address already in use )");
    else if(errorNum == EADDRNOTAVAIL)  strcpy(ecode, "(Cannot assign requested address )");
    else if(errorNum == ENETDOWN)   strcpy(ecode, "(Network is down )");
    else if(errorNum == ENETUNREACH)  strcpy(ecode, "(Network is unreachable )");
    else if(errorNum == ENETRESET)  strcpy(ecode, "(Network dropped connection because of reset )");
    else if(errorNum == ECONNABORTED)   strcpy(ecode, "(Software caused connection abort )");
    else if(errorNum == ECONNRESET) strcpy(ecode, "(Connection reset by peer )");
    else if(errorNum == ENOBUFS)    strcpy(ecode, "(No buffer space available )");
    else if(errorNum == EISCONN )   strcpy(ecode, "(Transport endpoint is already connected )");
    else if(errorNum == ENOTCONN)       strcpy(ecode, "(Transport endpoint is not connected )");
    else if(errorNum == ESHUTDOWN )     strcpy(ecode, "(Cannot send after transport endpoint shutdown )");
    else if(errorNum == ETOOMANYREFS )      strcpy(ecode, "(Too many references: cannot splice )");
    else if(errorNum == ETIMEDOUT)      strcpy(ecode, "(Connection timed out )");
    else if(errorNum == ECONNREFUSED)      strcpy(ecode, "(Connection refused )");
    else if(errorNum == EHOSTDOWN )  strcpy(ecode, "(Host is down )");
    else if(errorNum == EHOSTUNREACH)    strcpy(ecode, "(No route to host )");
    else if(errorNum == EALREADY)    strcpy(ecode, "(Operation already in progress )");
    else if(errorNum == EINPROGRESS)     strcpy(ecode, "(Operation now in progress )");
    else if(errorNum == ESTALE )       strcpy(ecode, "(Stale NFS file handle )");
    else if(errorNum == EUCLEAN )      strcpy(ecode, "(Structure needs cleaning )");
    else if(errorNum == ENOTNAM )      strcpy(ecode, "(Not a XENIX named type file )");
    else if(errorNum == ENAVAIL  )     strcpy(ecode, "(No XENIX semaphores available )");
    else if(errorNum == EISNAM  )     strcpy(ecode, "(Is a named type file )");
    else if(errorNum == EREMOTEIO )  strcpy(ecode, "(Remote I/O error )");
    else if(errorNum == EDQUOT )  strcpy(ecode, "(Quota exceeded )");

    else if(errorNum == ENOMEDIUM)  strcpy(ecode, "(No medium found )");
    else if(errorNum == EMEDIUMTYPE ) strcpy(ecode, "(Wrong medium type )");
    else if(errorNum == ECANCELED)  strcpy(ecode, "(Operation Canceled )");
    else if(errorNum == ENOKEY   )  strcpy(ecode, "(Required key not available )");
    else if(errorNum == EKEYEXPIRED )  strcpy(ecode, "(Key has expired )");
    else if(errorNum == EKEYREVOKED )  strcpy(ecode, "(Key has been revoked )");
    else if(errorNum == EKEYREJECTED )   strcpy(ecode, "(Key was rejected by service )");

    else if(errorNum == EOWNERDEAD )   strcpy(ecode, "(Owner died )");
    else if(errorNum == ENOTRECOVERABLE )  strcpy(ecode, "(State not recoverable )");
}